### ISSUE TITLE
Maintain consistency of view resizer scale

### ISSUE THREAD

**Issue by imccunn** [williewheeler/battle-balloons-course#7]
In the Resizer class, we want to maintain consistency of the scale value. In tags week03 and week04, the scale value (K) is set to 4 and subsequent tags are set to 3. 

Set the value of K to be the same across all tags.

**Comment by williewheeler** [comment]
Reclassified as a bug. The screen won't fit on a normal laptop when k=4.

**Comment by williewheeler** [comment]
Fixed.
